export const ORBITAL_PERIOD_UNKNOWN_VALUE_PLACEHOLDER = 'unknown';
export const GRAVITY_UNKNOWN_VALUE_PLACEHOLDER = 'N/A';
export const POPULATION_UNKNOWN_VALUE_PLACEHOLDER = 'unknown';
export const SURFACE_WATER_UNKNOWN_VALUE_PLACEHOLDER = 'unknown';
